name: Gerby
on:
  - push
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Gerby
        run: |
          pip install git+https://github.com/gerby-project/plastex.git
      - name: Prepare the TeX files
        run: |
          make web
      - name: Run Gerby
        run: |
          plastex --renderer=Gerby book.tex

