name: Gerby
on:
  - push
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Prepare the TeX files
        run: |
          mkdir gerby
          make gerby
      - name: Run Gerby
        uses: xu-cheng/texlive-action/small@v1
        with:
          run: |
            pip install git+https://github.com/gerby-project/plastex.git
            cd gerby
            plastex --renderer=Gerby book.tex

